version: 2.1
orbs:
  node: circleci/node@4.0.0

jobs:
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn test
          name: Run Unit Tests
  lint:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn lint
          name: Run Lint
  sevmer_release:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn semantic-release
          name: Run Release

workflows:
  dev_branch:
    jobs:
      - lint:
          filters:
            branches:
              ignore:
                - master
      - test:
          filters:
            branches:
              ignore:
                - master
  master_merge:
    jobs:
      - lint:
          filters:
            branches:
              only:
                - master
      - test:
          filters:
            branches:
              only:
                - master
      - sevmer_release:
          requires:
            - lint
            - test
          filters:
            branches:
              only:
                - master
