version: 2.1
orbs:
  node: circleci/node@4.0.0

jobs:
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn test
          name: Run Unit Tests
  lint:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn lint
          name: Run Lint
  release:
    executor:
      name: node/default
      steps:
        - checkout
        - node/install-packages:
            pkg-manager: yarn
        - run:
          command: npm run semantic-release || true
          name: Release

workflows:
  dev_branch:
    jobs:
      - lint
      - test
    ignore:
      - master
  master_merge:
    jobs:
      - lint
      - test
      - release
    only:
      - master
