version: 2.1
orbs:
  node: circleci/node@4.0.0
  codecov: codecov/codecov@1.1.1
  snyk: snyk/snyk@0.0.10
jobs:
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn test:ci
          name: Run Unit Tests
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./reports/junit/
      - store_test_results:
          path: ./reports/junit/
      - store_artifacts:
          path: ./reports/junit
      - store_artifacts:
          path: ./coverage
      - codecov/upload:
          file: ./coverage/clover.xml
      - codecov/upload:
          file: ./coverage/lcov.info
  lint:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn lint
          name: Run Lint
  snyk_monitor:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - snyk/scan
  yarn_audit:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Run yarn audit
          command: yarn audit
  sevmer_release:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn semantic-release
          name: Run Release

workflows:
  dev_branch:
    jobs:
      - lint:
          filters:
            branches:
              ignore:
                - master
      - test:
          filters:
            branches:
              ignore:
                - master
      - snyk_monitor:
          requires:
            - lint
            - test
          filters:
            branches:
              ignore:
                - master
      - yarn_audit:
          requires:
            - lint
            - test
          filters:
            branches:
              ignore:
                - master
  master_merge:
    jobs:
      - lint:
          filters:
            branches:
              only:
                - master
      - test:
          filters:
            branches:
              only:
                - master
      - snyk_monitor:
          requires:
            - test
            - lint
          filters:
            branches:
              only:
                - master
      - yarn_audit:
          requires:
            - test
            - lint
          filters:
            branches:
              ignore:
                - master
      - sevmer_release:
          requires:
            - snyk_monitor
            - yarn_audit
          filters:
            branches:
              only:
                - master
